# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "anyio" = super.buildPythonPackage rec {
    pname = "anyio";
    version = "4.11.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/15/b3/9b1a8074496371342ec1e796a96f99c82c945a339cd81a8e73de28b4cf9e/anyio-4.11.0-py3-none-any.whl";
      sha256 = "1z6473na3mqrxbflnninc84cs39gqcxlwka10n9i9m169mpyk1q2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."exceptiongroup"
      self."idna"
      self."sniffio"
      self."typing-extensions"
    ];
  };
  "certifi" = super.buildPythonPackage rec {
    pname = "certifi";
    version = "2025.11.12";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/70/7d/9bc192684cea499815ff478dfcdc13835ddf401365057044fb721ec6bddb/certifi-2025.11.12-py3-none-any.whl";
      sha256 = "0jrd0qnryi4mryf91nx6vgw0x0ppq8ppiv5pjqnmrg8b0f88gplp";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "exceptiongroup" = super.buildPythonPackage rec {
    pname = "exceptiongroup";
    version = "1.3.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8a/0e/97c33bf5009bdbac74fd2beace167cab3f978feb69cc36f1ef79360d6c4e/exceptiongroup-1.3.1-py3-none-any.whl";
      sha256 = "161mfwnghxs52jjvffv3zgglw30xf2jx71s976c1wy3ns8xrm8x7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."typing-extensions"
    ];
  };
  "h11" = super.buildPythonPackage rec {
    pname = "h11";
    version = "0.14.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/95/04/ff642e65ad6b90db43e668d70ffb6736436c7ce41fcc549f4e9472234127/h11-0.14.0-py3-none-any.whl";
      sha256 = "0qd7z9p38dwx215048q708vd1sn2abdh1mb3hg66ii2ip324mzp3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "httpcore" = super.buildPythonPackage rec {
    pname = "httpcore";
    version = "0.16.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/04/7e/ef97af4623024e8159993b3114ce208de4f677098ae058ec5882a1bf7605/httpcore-0.16.3-py3-none-any.whl";
      sha256 = "1h4xjk1b57p1sxxphz146x8camkh66wgxr5xhjh8m4sag04bf7ys";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."anyio"
      self."certifi"
      self."h11"
      self."sniffio"
    ];
  };
  "httpx" = super.buildPythonPackage rec {
    pname = "httpx";
    version = "0.23.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ac/a2/0260c0f5d73bdf06e8d3fc1013a82b9f0633dc21750c9e3f3cb1dba7bb8c/httpx-0.23.3-py3-none-any.whl";
      sha256 = "1mhhwfrrkd3vl394gsal06jana9xkf3gjsndy0jflm0jkg7gq4d2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."certifi"
      self."httpcore"
      self."rfc3986"
      self."sniffio"
    ];
  };
  "idna" = super.buildPythonPackage rec {
    pname = "idna";
    version = "3.11";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0e/61/66938bbb5fc52dbdf84594873d5b51fb1f7c7794e9c0f5bd885f30bc507b/idna-3.11-py3-none-any.whl";
      sha256 = "1sipr9kdjcmwjm3lc6dx83qk6j4dq7lnyvhy15jazvwxkps8f6kp";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "innertube" = super.buildPythonPackage rec {
    pname = "innertube";
    version = "2.1.19";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/45/fc/e670fa42c51260e34b88a97f7f4c896ca913de8aa3cb94a751fa58f4e9f6/innertube-2.1.19-py3-none-any.whl";
      sha256 = "05qk51kigndc2qhg80fs2i135fgzlgspy4qbhb0qcgwsksj913aw";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."httpx"
      self."mediate"
    ];
  };
  "mediate" = super.buildPythonPackage rec {
    pname = "mediate";
    version = "0.1.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0b/ed/63f72682ab3b2db30d83b45eea470bb0a90e4b06dd5e943cd1ae50b7e2a5/mediate-0.1.8-py3-none-any.whl";
      sha256 = "1aqzsgy615wyrbbihin8mgqxijl2yhc642xiayzp91z9q1zr8qwq";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."roster"
    ];
  };
  "rfc3986" = super.buildPythonPackage rec {
    pname = "rfc3986";
    version = "1.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c4/e5/63ca2c4edf4e00657584608bee1001302bbf8c5f569340b78304f2f446cb/rfc3986-1.5.0-py2.py3-none-any.whl";
      sha256 = "15raf577150bdnjqvr89n9xnc2cllw5dy4mh32r3ihhxbcgnwvd8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."idna"
    ];
  };
  "roster" = super.buildPythonPackage rec {
    pname = "roster";
    version = "0.1.11";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/69/2a/df77b20618387e2a7d3c2f43131a2a899b440969350fda72af29c5aa737c/roster-0.1.11-py3-none-any.whl";
      sha256 = "1fhmlcv1j5f9bmfdxfgk5mnds5j6wzkbkrr7ywplb55nagzw60s7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "sniffio" = super.buildPythonPackage rec {
    pname = "sniffio";
    version = "1.3.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e9/44/75a9c9421471a6c4805dbf2356f7c181a29c1879239abab1ea2cc8f38b40/sniffio-1.3.1-py3-none-any.whl";
      sha256 = "18i50l85yppn9w1ily8m342yd577h0bg8y24hkfzvq7is4ca8v9g";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "typing-extensions" = super.buildPythonPackage rec {
    pname = "typing-extensions";
    version = "4.15.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/18/67/36e9267722cc04a6b9f15c7f3441c2363321a3ea07da7ae0c0707beb2a9c/typing_extensions-4.15.0-py3-none-any.whl";
      sha256 = "0j75qhcc0p627f464gd7kjcirdzcga5zl32a0w4ann2phk31kyph";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
